### ISSUE TITLE
add c++ code for facebook1.java

### ISSUE THREAD

**Issue by Manish-Rawat-1186** [heyhooman/0xDSA#12]
add c++ code for trapping rainwater problems in facebook1.java

**Comment by SarthakPandey2002** [comment]
class Solution {
public:
    int trap(vector<int>& height) {
        int n=height.size();
        int ans=0;
        vector<int>leftMax(n);
        vector<int>rightMax(n);
        int sar=INT_MIN;
        for(int i=0;i<n;i++){
            sar=max(sar,height[i]);
            leftMax[i]=sar;
        }
        sar=INT_MIN;
        for(int i=n-1;i>=0;i--){
            sar=max(sar,height[i]);
            rightMax[i]=sar;
        }
        for(int i=0;i<n;i++){
            int temp=min(leftMax[i],rightMax[i]);
            ans+=abs(height[i]-temp);
        }
        return ans;
    }
};
